on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      uses: sigma/vsce-publish-action@v0.0.2
      with:
        vsce_token: ${{ secrets.VSCE_TOKEN }}
